//The program would output error, foo is inside the scope of the {} and console.log is outside of the scope
